spring:
  application:
    name: rennixing
  jpa:
    #开启SQL语句输出
    show-sql: true
    hibernate:
      #指定数据库表的创建和更新策略
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:heima;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: mima
  sql:
    init:
      data-locations: classpath:db/init.sql